from .base import *

DEBUG = False

ALLOWED_HOSTS = ["*"]
CORS_ALLOW_ALL_ORIGINS = True
C0RS_ALLOW_CREDENTIALS = True
ACCOUNT_EMAIL_VERIFICATION = "none"

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Static and media files
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "mediafiles"
